spring.application.name=redis-url-shortener
server.port=8081
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6382}
app.base-url=${APP_BASE_URL:http://localhost:8081}
