spring.application.name=redis-url-shortener
server.port=${PORT:8081}
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6382}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}
spring.data.redis.timeout=10s
spring.data.redis.connect-timeout=10s
app.base-url=${APP_BASE_URL:http://localhost:8081}
